-- SUPABASE SCHEMA SCHEMA FOR PORTFOLIO MANAGEMENT SYSTEM
-- Copy-paste this script into your Supabase SQL Editor and run it.

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--------------------------------------------------
-- 1. TABLES SETUP
--------------------------------------------------

-- Profiles Table (Single row or admin profile mapped by UID)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    tagline TEXT,
    about_me TEXT,
    phone TEXT,
    email TEXT,
    location TEXT,
    github_url TEXT,
    linkedin_url TEXT,
    avatar_url TEXT,
    resume_url TEXT,
    role_titles TEXT[] DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- 'Programming', 'Frontend', 'Backend', 'Database', 'Tools'
    icon TEXT,              -- Name of Lucide Icon
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    technologies TEXT[] DEFAULT '{}',
    github_url TEXT NOT NULL,
    live_demo_url TEXT,
    image_url TEXT,
    metrics TEXT[] DEFAULT '{}',
    is_featured BOOLEAN DEFAULT FALSE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Experience Table
CREATE TABLE IF NOT EXISTS public.experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company TEXT NOT NULL,
    role TEXT NOT NULL,
    duration TEXT NOT NULL, -- e.g. "Dec 2025 - Mar 2026"
    description TEXT,
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Education Table
CREATE TABLE IF NOT EXISTS public.education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree TEXT NOT NULL,
    field TEXT NOT NULL,
    institution TEXT NOT NULL,
    metric TEXT NOT NULL,    -- e.g. "CGPA: 7.8"
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Achievements Table
CREATE TABLE IF NOT EXISTS public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL, -- 'Academics', 'Professional Experience', 'Technical Expertise'
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Messages Table (Visitor contact form submissions)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Settings Table (General parameters like DSASolved numbers)
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------
-- 2. ROW LEVEL SECURITY (RLS) POLICIES
--------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Helper Function to check if user is the admin dynamically via metadata role claim
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN SECURITY DEFINER AS $$
BEGIN
  RETURN (
    auth.role() = 'authenticated' AND 
    (
      coalesce(
        auth.jwt() -> 'user_metadata' ->> 'role', 
        auth.jwt() -> 'app_metadata' ->> 'role'
      ) = 'admin'
    )
  );
END;
$$ LANGUAGE plpgsql;

-- Public read access policies
CREATE POLICY "Allow public read access on profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public read access on skills" ON public.skills FOR SELECT USING (true);
CREATE POLICY "Allow public read access on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public read access on experience" ON public.experience FOR SELECT USING (true);
CREATE POLICY "Allow public read access on education" ON public.education FOR SELECT USING (true);
CREATE POLICY "Allow public read access on achievements" ON public.achievements FOR SELECT USING (true);
CREATE POLICY "Allow public read access on settings" ON public.settings FOR SELECT USING (true);

-- Admin write access policies
CREATE POLICY "Allow admin write access on profiles" ON public.profiles FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin write access on skills" ON public.skills FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin write access on projects" ON public.projects FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin write access on experience" ON public.experience FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin write access on education" ON public.education FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin write access on achievements" ON public.achievements FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin write access on settings" ON public.settings FOR ALL USING (public.is_admin());

-- Contact messages policies
CREATE POLICY "Allow public anonymous insertion on messages" ON public.messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin view and delete on messages" ON public.messages FOR ALL USING (public.is_admin());

--------------------------------------------------
-- 3. STORAGE SETUP & POLICIES
--------------------------------------------------

-- Ensure the public bucket "portfolio-assets" exists
-- Note: Run this chunk if you have permissions, otherwise create "portfolio-assets" bucket via the storage panel.
INSERT INTO storage.buckets (id, name, public) 
VALUES ('portfolio-assets', 'portfolio-assets', true)
ON CONFLICT (id) DO NOTHING;

-- Storage objects policies for "portfolio-assets" bucket
CREATE POLICY "Allow public read access on storage assets" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'portfolio-assets');

CREATE POLICY "Allow admin modifications on storage assets" 
ON storage.objects FOR ALL 
USING (bucket_id = 'portfolio-assets' AND public.is_admin());

--------------------------------------------------
-- 4. INSERT DEFAULT SEED DATA
-- (Fallback seeding so that portfolio initializes with existing content)
--------------------------------------------------

-- Default settings (DSA scores, etc.)
INSERT INTO public.settings (key, value) VALUES 
('leetcode_solved', '0'),
('hackerrank_solved', '0'),
('leetcode_url', 'https://leetcode.com/u/karthik-ganji/'),
('hackerrank_url', 'https://www.hackerrank.com/profile/ganjikarthik999')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Default profile record
INSERT INTO public.profiles (id, name, tagline, about_me, phone, email, location, github_url, linkedin_url, role_titles)
VALUES (
    '5f41defa-4351-4e72-855c-681787822530', -- Static UUID matching conversation session or default
    'Karthik Ganji',
    'Building scalable web applications, backend systems, and intelligent software solutions.',
    'Computer Science graduate passionate about software engineering, backend systems, full-stack development, and machine learning. Experienced in building applications using Java, Python, React, FastAPI, Node.js, MongoDB, and modern development tools. Interested in software development, cloud technologies, distributed systems, and scalable architectures.',
    '+91 9700604248',
    'ganjikarthik999@gmail.com',
    'Chirala, Andhra Pradesh, India',
    'https://github.com/karthik-ganji',
    'https://linkedin.com/in/karthik-ganji',
    ARRAY['Software Engineer', 'Full Stack Developer', 'Java Developer']
) ON CONFLICT DO NOTHING;
